import YAML from 'yaml';

function generateYAMLCommentBlock(): string {
  return `# This configuration was generated by eslint-todo-generator
#
# on ${new Date().toISOString()}.
# generator version: {TODO};
# eslint version: {TODO};
#
# It contains all the known ESLint errors/warnings, and prevents them from
# showing up as errors until devs can remove them from the code base.
# Remove specific errors or entire file entries as you fix the offences.
`;
}

export function renderAsYAML(object: any): string {
  const renderConfiguration = YAML.stringify(object);
  return `${generateYAMLCommentBlock()}${renderConfiguration}`;
}

export function renderAsJSON(object: any): string {
  return `${JSON.stringify(object, null, 2)}`;
}
